### ISSUE TITLE
Problem with solidus 2.1.0.beta1 and solidus_static_content

### ISSUE THREAD

**Issue by sechix** [solidusio-contrib/solidus_static_content#5] opened 2016-12-18 17:36 UTC
I have error running solidus store in frontend and in pages section.
I think is due to solidus version 2.1.0.beta1 because I created a new solidus store to test only with solidus_static_content and get the same error.

ActiveRecord::StatementInvalid in Spree::StaticContentController#show
PG::UndefinedTable: ERROR: relation "spree_pages" does not exist LINE 8: WHERE a.attrelid = '"spree_pages"'::regclass ^ : SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod, (SELECT c.collname FROM pg_collation c, pg_type t WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation), col_description(a.attrelid, a.attnum) AS comment FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum WHERE a.attrelid = '"spree_pages"'::regclass AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum

**Comment by tvdeyen** [comment] 2016-12-18 19:28
Duplicate of #4

Please try the solution posted in #4

Closing

**Closed by tvdeyen** 2016-12-18 19:28 UTC
